repos:

- repo: https://github.com/pre-commit/pre-commit-hooks
  rev: v4.4.0
  hooks:
  - id: end-of-file-fixer
    exclude: .*\.ipynb
  - id: trailing-whitespace

- repo: https://github.com/psf/black
  rev: 23.1.0
  hooks:
    - id: black
      language_version: python3.10

- repo: https://github.com/charliermarsh/ruff-pre-commit
  rev: "v0.0.259"
  hooks:
    - id: ruff
      args: [--fix]
