REGION_PROBABILITIES: ldt_external_destchoice_probabilities.csv

REGION_CATEGORIES:
  - NAME: Central
  - NAME: NE
  - NAME: NW
  - NAME: SE
  - NAME: SW

# land use keys (need to determine whether a taz is internal or external)
# should be binary--1 if in area, 0 if not
MODEL_AREA_KEY: "MODELAREA"
# skim category keys (want some car time measurement between tazs)
SEGMENT_KEY: "PK"
SKIM_KEY: "CAR_DIST"
