# ldt_internal_mode_choice.yaml

SPEC: ldt_internal_mode_choice.csv
COEFFICIENTS: ldt_internal_mode_choice_coefficients.csv
COEFFICIENT_TEMPLATE: ldt_internal_mode_choice_coefficients_template.csv

LOGIT_TYPE: NL

NESTS:
  name: root
  coefficient: coef_nest_root
  alternatives: # automobile, air, walk to tran- sit, drive to transit, walk to high-speed rail, and drive to high-speed rail.
    - PRIVATEAUTO
    - AIR
    - name: GROUND
      coefficient:  coef_nest_GROUND
      alternatives:
        - name: TRANSIT
          coefficient: coef_nest_TRANSIT
          alternatives:
          - WALK_TRANSIT
          - DRIVE_TRANSIT
        - name: HSR
          coefficient: coef_nest_HSR
          alternatives:
          - WALK_HSR
          - DRIVE_HSR

CONSTANTS:
  orig_col_name: origin
  dest_col_name: destination
  min_waitTime: 0
  max_waitTime: 50


# to reduce memory needs filter chooser table to these fields
TOURS_MERGED_CHOOSER_COLUMNS:
  - income
  - auto_ownership

MODE_CHOICE_LOGSUM_COLUMN_NAME: ldt_mode_choice_logsum

preprocessor:  # None

# to reduce memory needs filter chooser table to these fields
LOGSUM_CHOOSER_COLUMNS:  # TODO trim this list
  - household_id
  - SEX
  - AGE
  - SCH
  - ESR
  - NAICSP02
  - SOCP10
  - SW_UNSPLIT_IND
  - SW_OCCUP
  - SW_SPLIT_IND
  - home_zone_id
  - value_of_time
  - person_num_in_hh
  - ldt_tour_gen_person_WORKRELATED
  - ldt_tour_gen_person_OTHER
  - ldt_pattern_person_WORKRELATED
  - ldt_pattern_person_OTHER
  - ldt_pattern
  - ldt_start_hour
  - ldt_end_hour
  - internal_external
  - external_destchoice
  - hhsize
  - INCOME
  - BLD
  - sample_rate
  - income_segment
  - median_value_of_time
  - hh_value_of_time
  - num_workers
  - num_students
  - num_drivers
  - income_in_thousands
  - min_person_id
  - auto_ownership
  - ldt_tour_gen_household
  - ldt_pattern_household
  - auPkTotal
  - auOpTotal
  - MODELAREA
  - CORDONZONE
  - AMZ
  - LDTdistrict
  - STATE
  - AreaType
  - Total_Employment
  - Utlities_Services
  - Construction
  - Transportation_Handling
  - Health_Care
  - Other_Services
  - Government_Services
  - Highschool_Education
  - College_Education
  - Hotel_Accomodation
  - Agriculture_Production
  - Agriculture_Office
  - Metal_Production
  - Metal_Office
  - Light_Industry_Production
  - Light_Industry_Office
  - Heavy_Industry_Production
  - Heavy_Industry_Office
  - Transportation_Equipment_Production
  - Transportation_Equipment_Office
  - Wholesale_Production
  - Wholesale_Office
  - Retail_Production
  - Retail_Office
  - CUBE_N
  - ETAZ_NAME
  - TerminalTime
  - IMPLANTYPE
  - IMPLANZONE
  - FAF3_AGGR
  - CENSUSPOP
  - HHlt20K1to2
  - HHlt20K3plus
  - HH20to40K1to2
  - HH20to40K3plus
  - HH40to60K1to2
  - HH40to60K3plus
  - HH60to75K1to2
  - HH60to75K3plus
  - HH75to100K1to2
  - HH75to100K3plus
  - HH100Kplus1to2
  - HH100Kplus3plus
  - TotHH
  - tot_hh
