# no spec or coefficients needed; this model is purely probabilistic
CONSTANTS:
    # probabilities of each pattern type
    COMPLETE: 0.0248
    BEGIN: 0.0237
    END: 0.0203
    AWAY: 0.0790
    # NOTOUR = 0.8521
