SAMPLE_SPEC: ldt_internal_tour_destination_sample.csv
SPEC: ldt_internal_tour_destination.csv
COEFFICIENTS: ldt_internal_tour_destination_coefficients.csv

SAMPLE_SIZE: 30

SIZE_TERM_SELECTOR: ldt
SIZE_TERM_PATH: internal_destination_choice_size_terms.csv

# we can't use use household income_segment as this will also be set for non-workers
CHOOSER_SEGMENT_COLUMN_NAME: ldt_tour_segment

# optional (comment out if not desired)
DEST_CHOICE_LOGSUM_COLUMN_NAME: destination_logsum

# comment out DEST_CHOICE_LOGSUM_COLUMN_NAME if saved alt logsum table
DEST_CHOICE_SAMPLE_TABLE_NAME: tour_destination_sample

preprocessor:
  SPEC: ldt_internal_tour_destination_annotate_tours_preprocessor.csv
  DF: longdist_tours
  TABLES:
    - persons

annotate_ldt_tours:
  SPEC: ldt_internal_tour_destination_annotate_tours_postprocessor.csv
  DF: longdist_tours
  TABLES:
    - persons

# segments here are 2-tuples, they give
#   `segment_name` for destination segmenting, and
#   `tour_purpose` for mode segmenting
SEGMENTS:
  # household tours are sub-segmented only by daytrip / overnight
  - [household_day, household]
  - [household_overnight, household]
  # individual work related tours are sub-segmented by daytrip / overnight and worker industry category
  - [workrelated_day_0, person_workrelated]         # not employed
  - [workrelated_day_1, person_workrelated]         # agriculture production
  - [workrelated_day_2, person_workrelated]         # agriculture office
  - [workrelated_day_3, person_workrelated]         # metal production
  - [workrelated_day_4, person_workrelated]         # metla office
  - [workrelated_day_5, person_workrelated]         # light industry production
  - [workrelated_day_6, person_workrelated]         # light industry office
  - [workrelated_day_7, person_workrelated]         # heavy industry production
  - [workrelated_day_8, person_workrelated]         # heavy industry office
  - [workrelated_day_9, person_workrelated]         # transportation equipment production
  - [workrelated_day_10, person_workrelated]        # transportation equipement office
  - [workrelated_day_11, person_workrelated]        # wholesale production
  - [workrelated_day_12, person_workrelated]        # wholesale office
  - [workrelated_day_13, person_workrelated]        # retail production
  - [workrelated_day_14, person_workrelated]        # retail office
  - [workrelated_day_15, person_workrelated]        # hotel/accomodation
  - [workrelated_day_16, person_workrelated]        # construction
  - [workrelated_day_17, person_workrelated]        # heatlhcare
  - [workrelated_day_18, person_workrelated]        # tarnsportation handling
  - [workrelated_day_19, person_workrelated]        # utilities
  - [workrelated_day_20, person_workrelated]        # other services
  - [workrelated_day_21, person_workrelated]        # primary education
  - [workrelated_day_22, person_workrelated]        # post-secondary education
  - [workrelated_day_23, person_workrelated]        # government
  - [workrelated_overnight_0, person_workrelated]         # not employed
  - [workrelated_overnight_1, person_workrelated]         # agriculture production
  - [workrelated_overnight_2, person_workrelated]         # agriculture office
  - [workrelated_overnight_3, person_workrelated]         # metal production
  - [workrelated_overnight_4, person_workrelated]         # metla office
  - [workrelated_overnight_5, person_workrelated]         # light industry production
  - [workrelated_overnight_6, person_workrelated]         # light industry office
  - [workrelated_overnight_7, person_workrelated]         # heavy industry production
  - [workrelated_overnight_8, person_workrelated]         # heavy industry office
  - [workrelated_overnight_9, person_workrelated]         # transportation equipment production
  - [workrelated_overnight_10, person_workrelated]        # transportation equipement office
  - [workrelated_overnight_11, person_workrelated]        # wholesale production
  - [workrelated_overnight_12, person_workrelated]        # wholesale office
  - [workrelated_overnight_13, person_workrelated]        # retail production
  - [workrelated_overnight_14, person_workrelated]        # retail office
  - [workrelated_overnight_15, person_workrelated]        # hotel/accomodation
  - [workrelated_overnight_16, person_workrelated]        # construction
  - [workrelated_overnight_17, person_workrelated]        # heatlhcare
  - [workrelated_overnight_18, person_workrelated]        # tarnsportation handling
  - [workrelated_overnight_19, person_workrelated]        # utilities
  - [workrelated_overnight_20, person_workrelated]        # other services
  - [workrelated_overnight_21, person_workrelated]        # primary education
  - [workrelated_overnight_22, person_workrelated]        # post-secondary education
  - [workrelated_overnight_23, person_workrelated]        # government
  # individual other tours are sub-segmented by daytrip / overnight and student status
  - [other_day_student, person_other]
  - [other_overnight_student, person_other]
  - [other_day_nonstudent, person_other]
  - [other_overnight_nonstudent, person_other]


SIMULATE_CHOOSER_COLUMNS:
  - tour_type
  - home_zone_id
  - household_id
  - person_id
  - ldt_pattern
  - ldt_start_hour
  - ldt_end_hour

LOGSUM_SETTINGS: ldt_internal_mode_choice.yaml

# model-specific logsum-related settings
CHOOSER_ORIG_COL_NAME: home_zone_id
ALT_DEST_COL_NAME: alt_dest
IN_PERIOD: 0
OUT_PERIOD: 0
