SPEC: ldt_internal_external.csv
COEFFICIENTS: ldt_internal_external_coefficients.csv
COEFFICIENT_TEMPLATE: ldt_internal_external_coefficient_template.csv

LOGIT_TYPE: MNL

CONSTANTS:
  DUMMY_CONSTANT: 1

# land use keys (need to determine whether a taz is internal or external)
MODEL_AREA_KEY: "MODELAREA"
# skim category keys (want some car time measurement between tazs)
SEGMENT_KEY: "PK"
SKIM_KEY: "CAR_TIME"
